# Generated by Django 4.2.16 on 2024-10-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='myapp.course'),
        ),
    ]
