# Generated by Django 4.2.16 on 2024-10-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_users_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='teacherImage',
            field=models.ImageField(default='uploads/default_teacher_image.jpg', upload_to='uploads/'),
        ),
    ]
