# Generated by Django 4.2.16 on 2024-11-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=300)),
                ('house_cover_image', models.ImageField(upload_to='uploads/')),
                ('phone', models.CharField(max_length=300, null=True)),
                ('ownerImage', models.ImageField(default='uploads/default_teacher_image.jpg', upload_to='uploads/')),
                ('owner_name', models.CharField(max_length=300, null=True)),
                ('text_location', models.TextField()),
                ('map_location', models.TextField()),
                ('bigDescription', models.TextField(null=True)),
                ('rooms', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=250)),
                ('flats', models.ManyToManyField(related_name='owners', to='myapp.flat')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/rooms/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='myapp.flat')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
