# Generated by Django 4.2.16 on 2024-11-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_bigdescription_flat_big_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='room_images',
            field=models.TextField(default='[]'),
        ),
    ]
