# Generated by Django 4.2.16 on 2024-11-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_flat_room_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='room_images',
        ),
        migrations.AddField(
            model_name='flat',
            name='room_image1',
            field=models.ImageField(null=True, upload_to='uploads/rooms/'),
        ),
        migrations.AddField(
            model_name='flat',
            name='room_image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rooms/'),
        ),
        migrations.AddField(
            model_name='flat',
            name='room_image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rooms/'),
        ),
        migrations.AddField(
            model_name='flat',
            name='room_image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rooms/'),
        ),
        migrations.AddField(
            model_name='flat',
            name='room_image5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rooms/'),
        ),
        migrations.AddField(
            model_name='flat',
            name='room_video',
            field=models.FileField(null=True, upload_to='uploads/rooms/'),
        ),
    ]
