# Generated by Django 4.2.16 on 2024-11-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='Image',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
