# Generated by Django 4.2.16 on 2024-12-04 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0028_alter_flat_bigdescription_alter_flat_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='bigDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='house_cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='house_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flat',
            name='ownerImage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_image1',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_image2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_image3',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_image4',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_image5',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='upazila',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
