# Generated by Django 4.2.16 on 2024-10-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_course_teacher_course_teacherimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bigDescription',
            field=models.TextField(null=True),
        ),
    ]
