# Generated by Django 4.2.16 on 2024-10-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_course_bigdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
