# Generated by Django 4.2.16 on 2024-11-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_owner_flats_flat_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='bigDescription',
            new_name='big_description',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='ownerImage',
            new_name='owner_image',
        ),
        migrations.AddField(
            model_name='flat',
            name='room_images',
            field=models.ImageField(upload_to='uploads/rooms/', null=True, blank=True),
        ),
        migrations.DeleteModel(
            name='RoomImage',
        ),
    ]
