# Generated by Django 4.2.16 on 2024-11-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_flat_room_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='big_description',
            new_name='bigDescription',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='owner_image',
            new_name='ownerImage',
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_images',
            field=models.ImageField(upload_to='uploads/rooms/'),
        ),
    ]
