# Generated by Django 4.2.16 on 2024-11-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_big_description_flat_bigdescription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='room_images',
            field=models.FileField(upload_to='uploads/rooms/'),
        ),
    ]
