# Generated by Django 4.2.16 on 2024-12-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_owner_image_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='room_video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/rooms/'),
        ),
    ]
