# Generated by Django 4.2.16 on 2024-12-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_flat_room_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='district',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='flat',
            name='upazila',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
