# Generated by Django 4.2.16 on 2024-12-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_rename_image_owner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='house_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
