# Generated by Django 4.2.16 on 2024-12-04 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_flat_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='bigDescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='district',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='house_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='house_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(default=-11, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='myapp.owner'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='ownerImage',
            field=models.ImageField(default='uploads/default_teacher_image.jpg', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='phone',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_image1',
            field=models.ImageField(null=True, upload_to='uploads/rooms/'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rooms/'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rooms/'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_image4',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rooms/'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='room_image5',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/rooms/'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='upazila',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
